[build]
  command = "npm install"
  publish = "src"
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/html/index.html"
  status = 200

[[redirects]]
  from = "/matchups"
  to = "/html/matchups.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/html/admin.html"
  status = 200

[[redirects]]
  from = "/env"
  to = "/.netlify/functions/api/env"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/html/index.html"
  status = 200